version: '3'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: coforge
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"  # Expose MySQL on port 3306
    networks:
      - mynetwork
    volumes:
      - mysql-data:/var/lib/mysql  # Persistent data storage for MySQL

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: springboot-app
    depends_on:
      - mysql
    ports:
      - "8082:8082"  # Expose Spring Boot app on port 8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/coforge
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge  # Ensure the app and MySQL can communicate on this network

volumes:
  mysql-data:  # This volume is used for MySQL data persistence
